# 직업 전용 상점 설정 (구매/판매 가격 분리)
shops:
  # 직업별 상점
  explorer:
    items:  # 구매 가능 아이템
      - name: "지도"
        price: 100
        material: PAPER
        amount: 1
      - name: "나침반"
        price: 75
        material: COMPASS
        amount: 1
    sell:  # 판매 가격 (아이템별)
      PAPER: 5
      COMPASS: 30
      MAP: 40
      FILLED_MAP: 50

  carpenter:
    items:
      - name: "기본 도끼"
        price: 70
        material: IRON_AXE
        amount: 1
      - name: "목재 묶음"
        price: 25
        material: OAK_LOG
        amount: 16
    sell:
      OAK_LOG: 2
      SPRUCE_LOG: 2
      BIRCH_LOG: 2
      JUNGLE_LOG: 3
      ACACIA_LOG: 2
      DARK_OAK_LOG: 3
      OAK_PLANKS: 1
      STICK: 1

  miner:
    items:
      - name: "기본 곡괭이"
        price: 80
        material: IRON_PICKAXE
        amount: 1
      - name: "화약"
        price: 60
        material: GUNPOWDER
        amount: 8
    sell:
      COAL: 5
      IRON_ORE: 15
      GOLD_ORE: 25
      DIAMOND: 100
      EMERALD: 150
      LAPIS_LAZULI: 10
      REDSTONE: 8
      COPPER_ORE: 5
      DEEPSLATE_IRON_ORE: 18
      DEEPSLATE_GOLD_ORE: 28
      DEEPSLATE_DIAMOND_ORE: 110

  hunter:
    items:
      - name: "활"
        price: 90
        material: BOW
        amount: 1
      - name: "화살 묶음"
        price: 25
        material: ARROW
        amount: 64
    sell:
      LEATHER: 8
      BEEF: 6
      PORKCHOP: 6
      CHICKEN: 5
      MUTTON: 6
      RABBIT: 4
      FEATHER: 3
      BONE: 2
      STRING: 4

  farmer:
    items:
      - name: "씨앗 상자"
        price: 30
        material: WHEAT_SEEDS
        amount: 32
      - name: "비료"
        price: 20
        material: BONE_MEAL
        amount: 16
    sell:
      WHEAT: 3
      CARROT: 4
      POTATO: 4
      BEETROOT: 3
      MELON_SLICE: 2
      PUMPKIN: 8
      SUGAR_CANE: 3
      APPLE: 5

  fisher:
    items:
      - name: "낚싯대"
        price: 60
        material: FISHING_ROD
        amount: 1
      - name: "미끼 상자"
        price: 20
        material: ROTTEN_FLESH
        amount: 16
    sell:
      COD: 5
      SALMON: 8
      TROPICAL_FISH: 12
      PUFFERFISH: 15
      PRISMARINE_SHARD: 10
      PRISMARINE_CRYSTALS: 15
      NAUTILUS_SHELL: 50
      HEART_OF_THE_SEA: 200

  blacksmith:
    items:
      - name: "대장 도구 세트"
        price: 200
        material: ANVIL
        amount: 1
      - name: "강화 재료"
        price: 120
        material: IRON_INGOT
        amount: 16
    sell:
      IRON_INGOT: 10
      GOLD_INGOT: 20
      DIAMOND: 100
      NETHERITE_INGOT: 500
      IRON_SWORD: 30
      IRON_PICKAXE: 35
      IRON_AXE: 35
      IRON_HELMET: 25
      IRON_CHESTPLATE: 40

  alchemist:
    items:
      - name: "포션 재료 상자"
        price: 150
        material: BLAZE_POWDER
        amount: 8
      - name: "에센스"
        price: 200
        material: GHAST_TEAR
        amount: 4
    sell:
      NETHER_WART: 10
      BLAZE_POWDER: 20
      GHAST_TEAR: 50
      MAGMA_CREAM: 15
      SPIDER_EYE: 5
      FERMENTED_SPIDER_EYE: 10
      GLISTERING_MELON_SLICE: 8
      GOLDEN_CARROT: 12

  chef:
    items:
      - name: "고급 식재료"
        price: 120
        material: COOKED_BEEF
        amount: 16
      - name: "양념 세트"
        price: 40
        material: SUGAR
        amount: 16
    sell:
      COOKED_BEEF: 8
      COOKED_PORKCHOP: 8
      COOKED_CHICKEN: 7
      COOKED_MUTTON: 8
      BREAD: 5
      CAKE: 20
      COOKIE: 3
      PUMPKIN_PIE: 6

  # 전역 판매 가격 (모든 직업 공통)
  global:
    sell:
      DIRT: 1
      COBBLESTONE: 1
      STONE: 2
      SAND: 2
      GRAVEL: 2
      GLASS: 3
      WOOL: 5
      ROTTEN_FLESH: 1
      BONE: 2
      GUNPOWDER: 8